### ISSUE TITLE
Barra superior

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#1]
A barra com o Call to Action está com o comportamento inadequado. O comportamento deve ser assim:
- Ao rolar 100px para baixo mostrar a barra.
- Ao rolar para cima, quando estiver faltando 100px para chegar no topo, esconder a barra.
- O ícone de fechar deve estar totalmente à direita, pegando a largura fluida da página.
- O texto e formulário devem estar centralizados.
- No mobile a barra está quebrando.
- Mensagem de feedback de sucesso deve ser desta forma:
  ![image](https://cloud.githubusercontent.com/assets/1466491/12593395/03d16f76-c458-11e5-865a-0901f6e9c83e.png)
- Mensagem de feedback de erro deve ser desta forma:
  ![image](https://cloud.githubusercontent.com/assets/1466491/12593425/3535350c-c458-11e5-9263-e9accb5d401f.png)
- A barra precisa ficar por cima de todos os elementos da página. Veja este bug:

![image](https://cloud.githubusercontent.com/assets/1466491/12612499/57a82aa4-c4da-11e5-8a8a-faedbb4ef480.png)

**Comment by unaghii** [comment]
A parte do erro do email não deu pra deixar igual mas adaptei. O resto está ok.

**Comment by pedrohrezende** [comment]
- A barra não está sendo apresentada no mobile.
- A mensagem de erro continua com problema.
- Não seria possível criar 2 formulários diferentes, um pra lateral e outro pro topo?

![image](https://cloud.githubusercontent.com/assets/1466491/12625205/e9fac1fc-c519-11e5-9b80-9fe932348194.png)

**Comment by unaghii** [comment]
@pedrohrezende arrumei o erro. Estou confuso quanto ao o que é pra aparecer no mobile e o que não é.

**Comment by pedrohrezende** [comment]
É para apresentar a barra normalmente, porém responsiva. O texto acima e o form abaixo. Tal como neste exemplo:
![image](https://cloud.githubusercontent.com/assets/1466491/12655997/e6935640-c5e2-11e5-8c30-dc48e6299ca2.png)

**Comment by pedrohrezende** [comment]
Vc pode deixar de tratar este erro?

![image](https://cloud.githubusercontent.com/assets/1466491/12656062/4fae239e-c5e3-11e5-8b10-69f7de73adab.png)

Isso não seria considerado um erro, entende?

**Comment by unaghii** [comment]
@pedrohrezende devo deixar emails duplicados serem inseridos?

**Comment by pedrohrezende** [comment]
Eu não vejo problema, pois o cliente deve exportar a lista de emails para o Mailchimp, q fará esse tratamento.

**Comment by unaghii** [comment]
Feito.

**Comment by pedrohrezende** [comment]
Quando vou pra versão mobile estamos com 2 problemas:
- A barra aparece antes mesmo de rolar
- A barra ainda não está responsiva

![image](https://cloud.githubusercontent.com/assets/1466491/12681193/7d2e6aca-c694-11e5-931c-c3d911b2197f.png)

**Comment by unaghii** [comment]
Corrigido.

**Comment by pedrohrezende** [comment]
A msg de erro está quebrando o form tanto no Desktop quanto no mobile

![image](https://cloud.githubusercontent.com/assets/1466491/12688155/83bb96a2-c6bb-11e5-9dbd-0672f8ad5f70.png)

**Comment by unaghii** [comment]
Corrigi no desktop mas no mobile mas não vai ter jeito de manter porque o html é gerado novamente quando dá o submit e eu perco as alterações que fiz (deixar o botão ao lado do input)
