### ISSUE TITLE
Exit intent

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#10]
Ficou faltando também este plugin.

Ele deve ser acionado quando o usuário mover o cursor para fechar a aba ou sair do site.

![image](https://cloud.githubusercontent.com/assets/1466491/12593790/0a110e1c-c45a-11e5-9ea6-c55b7f87e58f.png)

**Comment by pedrohrezende** [comment]
@unaghii conseguiu trabalhar no exit intent?

**Comment by pedrohrezende** [comment]
@unaghii alguma novidade?

**Comment by unaghii** [comment]
Feito.

**Comment by pedrohrezende** [comment]
O exit intent só é apresentado uma vez. Depois que o usuário fechou, não apresentamos mais. Teria como cachear por 24h?

**Comment by pedrohrezende** [comment]
@unaghii Outro ponto, logo abaixo do botão onde está escrito "Não, obrigado, já estou 100% satisfeito com os meus resultados" deve ser um link q fecha o exit intent.

**Comment by pedrohrezende** [comment]
@unaghii aliás, podemos fazer por sessão do browser. Só exibe novamente depois q fechar e abrir o browser.

**Comment by unaghii** [comment]
@pedrohrezende fiz por cookie. 24h ou até ser atualizado.
