### ISSUE TITLE
Categorias

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#12]
As categorias no mobile deve ser apresentado de acordo com o q foi projetado.

![image](https://cloud.githubusercontent.com/assets/1466491/12595339/e4961526-c461-11e5-8884-8f9279fa4fb1.png)

Menu aberto

![image](https://cloud.githubusercontent.com/assets/1466491/12595353/f77dab22-c461-11e5-9675-a8b893182c3b.png)

Tudo isso está no PSD

**Comment by unaghii** [comment]
Feito.

**Comment by pedrohrezende** [comment]
O menu não está sendo exibido na versão mobile. Apenas na versão tablet.

![Uploading image.png…]()

**Comment by unaghii** [comment]
@pedrohrezende Aqui está aparecendo normalmente. Qual resolução está verificando?

**Comment by pedrohrezende** [comment]
Até 571px o menu está visível, de 570px pra baixo, fica escondido.

Estou usando o Chrome.

**Comment by unaghii** [comment]
Corrigido.

**Comment by pedrohrezende** [comment]
Quando simulo o menu no moble e volto pra desktop, as categorias somem:

![image](https://cloud.githubusercontent.com/assets/1466491/12727167/d078d9ca-c902-11e5-9365-c42e2e692fc4.png)

**Comment by unaghii** [comment]
Corrigido.
