### ISSUE TITLE
Navegar por categorias

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#13]
Ao clicar em alguma categoria, devemos manter o topo do Blog, incluir um texto acima da listagem e deixar a categoria selecionada como active (laranja)

![image](https://cloud.githubusercontent.com/assets/1466491/12612933/5c0850c6-c4dd-11e5-988d-5ad05fe854c7.png)

**Comment by unaghii** [comment]
Feito.
