### ISSUE TITLE
Resultado da busca

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#14]
- Seguir o mesmo conceito da navegação por categorias

![image](https://cloud.githubusercontent.com/assets/1466491/12612986/b082ce6a-c4dd-11e5-99dc-99c34df76f10.png)
- Ao não encontrar resultado, alterar o texto para: Resultado da busca: Nenhum artigo encontrado

**Comment by unaghii** [comment]
Feito.

**Comment by pedrohrezende** [comment]
@unaghii as issues fechadas já estão disponíveis em homolog?

**Comment by pedrohrezende** [comment]
- Fiz uma busca mas não apareceu o texto: Resultado da busca por "Termo pesquisado"
- Fazendo uma busca de algo que não existe também não apresentou o texto atualizado: Nenhum artigo encontrado para "Termo buscado"

**Comment by unaghii** [comment]
Corrigido. (Sim, as fechadas estão disponíveis)

**Comment by pedrohrezende** [comment]
Só mais um detalhe, Victor: Para uma busca que não retornar resultado, apresentar apenas a seguinte mensagem: Nenhum artigo encontrado para "Termo buscado"

**Comment by unaghii** [comment]
Feito.

**Comment by pedrohrezende** [comment]
Fala Victor, acho q não me expressei mt bem. A ideia é usar apenas uma frase, seguindo o mesmo padrão de quando houver um resultado encontrado.

![image](https://cloud.githubusercontent.com/assets/1466491/12656147/c913180c-c5e3-11e5-8ad5-b1bc02c093a8.png)

**Comment by unaghii** [comment]
Feito.
