### ISSUE TITLE
Disqus

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#16]
- Colocar o Disqus em português
- É possível remover o rodapé?
  ![image](https://cloud.githubusercontent.com/assets/1466491/12645883/18a7ed8c-c5b4-11e5-946a-c67324d3d9aa.png)

**Comment by unaghii** [comment]
- Tradução ativada
- Não é possível remover o rodapé pois ele está dentro de um iframe default do Disqus
