### ISSUE TITLE
Personalização do CTA slider

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#18]
Como posso personalizar este CTA?

Só encontrei a personalização do link para download do ebook, porém este CTA precisa ser genérico. Posso precisar alterar título, subtítulo e imagem, além do rótulo do botão.

![image](https://cloud.githubusercontent.com/assets/1466491/12721544/8c1ada64-c8e7-11e5-8b8f-a61671fa8f4a.png)

**Comment by unaghii** [comment]
Feito. Tá na aba "Ebook".

**Comment by pedrohrezende** [comment]
Ficou faltando o texto do botão.

**Comment by unaghii** [comment]
Verdade, esqueci. Coloquei lá.

**Comment by pedrohrezende** [comment]
Vc poderia alterar os textos desse CTA dentro do Admin?
Ao invés de Ebook - CTA Slider
Alterar todos os textos no formulário, de forma a deixar mais genérico mesmo.

**Comment by pedrohrezende** [comment]
Ebook = CTA Slider
Configurações do CTA de ebook = Configurações do CTA Slider
Título do box para download do ebook = Título
Descrição do box para download do ebook = Descrição
Texto do botão de download = Texto do botão
Link para download do ebook = Link do botão

Ah, ficou faltando tb a opção de alterar a imagem

**Comment by unaghii** [comment]
Feito.

**Comment by pedrohrezende** [comment]
@unaghii Uma outra dúvida: É possível termos um Slider pra Empresas e outro pra Instituições de ensino?

**Comment by unaghii** [comment]
Feito.

**Comment by pedrohrezende** [comment]
@unaghii o cliente precisou remover o CTA slider, pois ele está usando um plugin. No entanto quanto removo as informações no Admin, o CTA continua aparecendo. Vc poderia verificar isso, por favor?

![image](https://cloud.githubusercontent.com/assets/1466491/13430039/10b24534-dfa2-11e5-8f05-e9ecbf7bb262.png)

**Comment by unaghii** [comment]
Coloquei a condição de só aparecer quando pelo menos o título estiver setado.

**Comment by pedrohrezende** [comment]
Valeu @unaghii , muito obrigado.
