### ISSUE TITLE
Vídeo responsivo

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#19]
Victor, no post que criamos de exemplo inserimos um vídeo do vimeo, através do próprio WP.

No entanto o player não está responsivo.

![image](https://cloud.githubusercontent.com/assets/1466491/12723672/8a4336b4-c8f1-11e5-80a6-66f082075af8.png)

**Comment by unaghii** [comment]
Deve-se usar o shortcode que criei pro vídeo poder ficar responsivo:

[video link="https://vimeo.com/148245992"]

**Comment by pedrohrezende** [comment]
@unaghii Como esse shortcode é inserido?

**Comment by unaghii** [comment]
@pedrohrezende manualmente

**Comment by pedrohrezende** [comment]
E para o caso dos vídeos do Youtube? Deveria manter a proporção

![image](https://cloud.githubusercontent.com/assets/1466491/12729911/39fd10ca-c910-11e5-82f0-adbab6af0f25.png)

**Comment by unaghii** [comment]
Você usou o shortcode nesse exemplo?

**Comment by pedrohrezende** [comment]
Esse foi vc quem subiu

**Comment by unaghii** [comment]
Corrigi.
