### ISSUE TITLE
Tipos de postagem

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#2]
O Blog precisa ser projetado para ter 2 tipos de postagem:
- Empresas
- Instituições de ensino

![image](https://cloud.githubusercontent.com/assets/1466491/12592552/162281b4-c454-11e5-8eef-6973e655c4d1.png)

Clicando em empresas, deve apresentar todas as postagens de Empresas e o mesmo para Instituições de ensino.

Além disso, o cliente precisa trabalhar banners e CTAs específicos para cada um desses públicos. Lembra q comentei com vc sobre isso?

**Comment by pedrohrezende** [comment]
O usuário poderá acessar o blog por 2 caminhos:
- Empresas
- instituições de ensino

Ao acessar empresas, apresentar a listagem de posts relativos a "Empresas", assim como categorias específicas de empresa, CTA lateral específico de empresa, Barra superior com CTA específico de empresa e CTA Slider específico de empresa. A categoria "Empresas" não deve ser apresentada na lateral, apenas no menu global, no header. Além disso a categoria pai selecionada deve ficar ativa (com a borda laranja em baixo)  e neste caso não apresentar o texto "Artigos sobre Empresas"

![image](https://cloud.githubusercontent.com/assets/1466491/12646392/def86dca-c5b6-11e5-8e18-029ba15f1848.png)

**Comment by unaghii** [comment]
Feito. Todas as opções das categorias estão no menu 'Opções do tema'. Se elas estão vazias as configurações gerais são usadas.

**Comment by pedrohrezende** [comment]
Uma dúvida, @unaghii Precisamos ter para cada categoria Pai:
- Barra superior específica
- Um CTA lateral específico
- Um CTA slider específico

Do jeito que vc fez, me parece que está um pro site todo.

**Comment by unaghii** [comment]
@pedrohrezende no menu Opções do tema > Geral ( http://bitnami-wordpress-85c3.cloudapp.net/wp-admin/admin.php?page=_options&tab=1 ) tem as opções gerais.
No Opções do tema > Empresas ( http://bitnami-wordpress-85c3.cloudapp.net/wp-admin/admin.php?page=_options&tab=2 ) tem os mesmos campos só que para essa categoria. No caso de estarem vazios (como estão agora) os campos da aba "Geral" são usados.

**Comment by pedrohrezende** [comment]
Beleza @unaghii valeu!

**Comment by pedrohrezende** [comment]
Depois q mexi um pouco nestas áreas, alguns problemas apareceram, mesmo depois de eu restaurar a sessão:

![image](https://cloud.githubusercontent.com/assets/1466491/12688336/be4058b6-c6bc-11e5-825c-aae6ff064d7c.png)

**Comment by pedrohrezende** [comment]
Inseri os formulários na página Instituições de ensino, não preenchi mais nada. No entanto ele apresentou o titulo e subtitulo do geral, mas não apresentou a imagem.

**Comment by unaghii** [comment]
@pedrohrezende arrumei a imagem. De resto tá ok, né?

**Comment by pedrohrezende** [comment]
Está sim, @unaghii
