### ISSUE TITLE
Logos no rodapé - Mobile

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#20]
As logos no rodapé na versão mobile estão meio encavaladas. 

![image](https://cloud.githubusercontent.com/assets/1466491/12727034/047950ac-c902-11e5-8fa1-ade937470060.png)

Veja como foram projetadas:

![image](https://cloud.githubusercontent.com/assets/1466491/12727058/2658cf2c-c902-11e5-97f3-74caa940d392.png)

**Comment by unaghii** [comment]
Coloquei margens a mais. Veja se está bom agora, por favor.

**Comment by pedrohrezende** [comment]
Está ok agora
