### ISSUE TITLE
Legenda de fotos

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#22]
A legenda está com um fundo cinza e o texto não está com a formatação/espaçamento corretos.

![image](https://cloud.githubusercontent.com/assets/1466491/12750291/4e5295ee-c99d-11e5-8210-1a091569ea81.png)

Seguir este exemplo:

![image](https://cloud.githubusercontent.com/assets/1466491/12750276/4115282e-c99d-11e5-82de-95dfccb6e1bb.png)

**Comment by unaghii** [comment]
Feito.

**Comment by pedrohrezende** [comment]
Faltou só dar um espaçamento do texto pra foto, na parte superior:

![image](https://cloud.githubusercontent.com/assets/1466491/12756498/2518b064-c9bb-11e5-94c1-7373f6b82842.png)

**Comment by unaghii** [comment]
Feito
