### ISSUE TITLE
Resultado da busca: Vídeos

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#24]
Se o cliente subir o vídeo apenas, sem inseir nenhum texto, o resultado da busca apresenta o shortcode

![image](https://cloud.githubusercontent.com/assets/1466491/12756248/0833ab26-c9ba-11e5-8086-1c7ffdd11eb4.png)

**Comment by unaghii** [comment]
Isso não vai acontecer usando o campo que comentei no outro tópico.
