### ISSUE TITLE
CTA single post

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#26]
Victor, vi q vc criou a configuração específica para o CTA single post. Mas lembra q precisamos ter 1 pra Empresas e outra pra Instituições de ensino? O mesmo se aplica para o CTA slider.

**Comment by unaghii** [comment]
Feito. Os campos estão lá nas tabs das categorias no Opções do tema.

**Comment by pedrohrezende** [comment]
@unaghii Não teria como fazermos de uma forma um pouco diferente?

Talvez criando um fieldset no formulário, de forma a deixar os campos mais agrupados. Tirando as linhas q separam os campos q fazem parte de um CTA. Exemplo:

![image](https://cloud.githubusercontent.com/assets/1466491/12782194/97d93af6-ca60-11e5-8f14-b0acb2d2b547.png)

**Comment by unaghii** [comment]
@pedrohrezende deixei agrupado. Esse é mais perto da sua imagem que consigo deixar.

**Comment by pedrohrezende** [comment]
@unaghii Já melhorou bastante! Vc pode só ajustar os textos dos campos do CTA Slider?

**Comment by unaghii** [comment]
@pedrohrezende feito

**Comment by pedrohrezende** [comment]
Aqui apareceu vazio, vc sabe pq?

![image](https://cloud.githubusercontent.com/assets/1466491/12794279/6fed5b4a-ca9b-11e5-9666-4401f449a1f6.png)

**Comment by pedrohrezende** [comment]
@unaghii alguma novidade? Me parece que quando o form está vazio em Opções do Tema > Empresas ou Opções do Tema > Instituições de ensino, ele não pega as informações globais.

Verifique isso, por favor. Recebi um email do cliente hoje relatando exatamente este problema.

**Comment by unaghii** [comment]
@pedrohrezende corrigido.
