### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#27]
- Ao criar um vídeo no admin, é possível adicionar texto depois do player?
- Onde posso ordenar os vídeos que aparecem na sessão vídeos? Procurei na listagem de vídeos, mas não encontrei
- Tentei usar o gerenciador de comentários do Disquss e ele pediu usuário e senha. Vc havia dito q era plugin e que não precisava de usuário. Como faz pra gerenciar os comentários?
- Como funciona a regra de artigos e vídeos relacionados?

**Comment by unaghii** [comment]
Ao criar um vídeo no admin, é possível adicionar texto depois do player?
**Coloquei o vídeo pra aparecer antes do vídeo. Posso colocar pra aparecer depois, mas é uma das duas opções só.**

Onde posso ordenar os vídeos que aparecem na sessão vídeos? Procurei na listagem de vídeos, mas não encontrei
**Adicionei o campo "ordem"**

Tentei usar o gerenciador de comentários do Disquss e ele pediu usuário e senha. Vc havia dito q era plugin e que não precisava de usuário. Como faz pra gerenciar os comentários?
**Consegui aprovar e editar pelo painel aqui sem problemas. Como você tentou?**

Como funciona a regra de artigos e vídeos relacionados?
**Artigos e vídeos sob a mesma categoria.**

**Comment by pedrohrezende** [comment]
Coloquei o vídeo pra aparecer antes do vídeo. Posso colocar pra aparecer depois, mas é uma das duas opções só.
**Pode colocar depois**

Consegui aprovar e editar pelo painel aqui sem problemas. Como você tentou?
**Agora apareceu pra mim**

Como funciona a regra de artigos e vídeos relacionados?
**Não tem nenhum de categoria relacionada e mesmo assim aparece. Existe alguma outra regra?**

**Comment by unaghii** [comment]
Coloquei o vídeo pra aparecer antes do vídeo. Posso colocar pra aparecer depois, mas é uma das duas opções só.
- Pode colocar depois
  **\- - Feito**

Como funciona a regra de artigos e vídeos relacionados?
- Não tem nenhum de categoria relacionada e mesmo assim aparece. Existe alguma outra regra?
  **\- - Se não tem na categoria os primeiros posts são trazidos**

**Comment by pedrohrezende** [comment]
Entendi. Valeu demais!
