### ISSUE TITLE
Topo do Blog

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#3]
- A cor de fundo da foto está diferente da que projetamos no Layout
- A altura do topo está menor do projetado
- O título e subtítulo não estão com os espaçamentos corretos e também não estão centralizados na vertical.
- O botão da busca precisa ter o cursor hand

![image](https://cloud.githubusercontent.com/assets/1466491/12592644/7cae4bfc-c454-11e5-9488-14a0e491ce23.png)

**Comment by unaghii** [comment]
Feito.

**Comment by pedrohrezende** [comment]
Na versão mobile está comendo os textos. Me parece q está comendo os textos a medida que reduz a largura da tela

![image](https://cloud.githubusercontent.com/assets/1466491/12628761/e642c6ce-c52b-11e5-9f9f-45ed968c6393.png)

**Comment by unaghii** [comment]
Corrigido.
