### ISSUE TITLE
Publicar no nome de outro usuário

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#32]
É possível? Se sim, como?

**Comment by unaghii** [comment]
Só mudando o autor lá na edição de cada post mesmo.

**Comment by pedrohrezende** [comment]
@unaghii Como que altera o autor no post? Dentro do post eu não encontrei nenhum lugar para isso.

**Comment by pedrohrezende** [comment]
@unaghii consegue me explicar isso?

**Comment by unaghii** [comment]
@pedrohrezende tem que ir em Opções de tela e habilitar o campo Autor. Daí no rodapé da página vai aparecer um select pra mudar o autor, se desejar.

![screen shot 2016-02-12 at 12 42 41 am](https://cloud.githubusercontent.com/assets/5882214/12997592/02a2b2fa-d122-11e5-849a-4bed2ce69c88.png)

**Comment by pedrohrezende** [comment]
Valeu @unaghii
