### ISSUE TITLE
Inserção de java scritp

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#33]
@unaghii o cliente tb precisa adicionar um script no site. Onde ele pode ser inserido?

<script type="text/javascript" src="https://d335luupugsy2.cloudfront.net/js/integration/stable/rd-js-integration.min.js"></script>

<script type="text/javascript">
function bindform() {
    var form = jQuery('form[calss=”leadin-form-wrapper”]');
    if(form.length=1){
        RdIntegration.integrate('c2a61e6975a3658b5caf43c7a784e942', 'Leadin');
    }else{setTimeout(bindform, 1000);}
}
setTimeout(bindform, 1000);
</script>

**Comment by unaghii** [comment]
Pode inserir no campo do código do Analytics.
