### ISSUE TITLE
Posts: listagem

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#4]
- A descrição precisa ter 200 caracteres.

![image](https://cloud.githubusercontent.com/assets/1466491/12592873/7f4890b0-c455-11e5-8dce-188c63c84ed6.png)

**Comment by unaghii** [comment]
Feito.

**Comment by pedrohrezende** [comment]
Excedeu os 200 caracteres. Na versão desk dá em torno de 3 linhas de descrição.

![image](https://cloud.githubusercontent.com/assets/1466491/12622868/949f41d4-c50e-11e5-98e1-de9c643da129.png)

**Comment by unaghii** [comment]
Não havia subido quando fechei o tópico. Já está lá.

**Comment by pedrohrezende** [comment]
Pelo q estou vendo, está em torno de 160 caracteres. Teria como aumentar para 200? Assim ficamos com 3 linhas de descrição.

**Comment by unaghii** [comment]
Corrigido.
