### ISSUE TITLE
CTA da lateral

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#5]
- Ficou faltando o texto abaixo do título "Cadastre seu email agora:"

![image](https://cloud.githubusercontent.com/assets/1466491/12592969/ed7a4b82-c455-11e5-8142-85cd6e9c4ed6.png)
- O campo de email está com problema: Quando insiro alguma informação no campo, o placeholder "Email" permanece visível.
  ![image](https://cloud.githubusercontent.com/assets/1466491/12592964/e852c1de-c455-11e5-94dd-7d71eda6a20c.png)
- A mensagem de erro está dando problema. Preencho o formulário na lateral e o erro aparece no topo

![image](https://cloud.githubusercontent.com/assets/1466491/12593158/c1782706-c456-11e5-86c9-9ce383c1a5f5.png)
- O feedback de erro deve ser assim:

![image](https://cloud.githubusercontent.com/assets/1466491/12593471/66021e48-c458-11e5-8a02-d99dcddb45d4.png)
- A mensagem de sucesso também está problemática. O feedback deve ser em apenas um formulário além de ter um design diferente.

![image](https://cloud.githubusercontent.com/assets/1466491/12593127/a3eeeecc-c456-11e5-9bef-06bce97c0fbf.png)
- O feedback de sucesso deve ser assim:

![image](https://cloud.githubusercontent.com/assets/1466491/12593288/754e0c8c-c457-11e5-8241-b958cbc2ba50.png)

**Comment by unaghii** [comment]
Feito. Porém como são o mesmo formulário no topo e na sidebar as mensagens de erro e sucesso permanecem aparecendo ao mesmo tempo.

**Comment by pedrohrezende** [comment]
@unaghii Sugiro então termos 2 formulários diferentes.

**Comment by unaghii** [comment]
@pedrohrezende com o mesmo propósito e campos iguais?

**Comment by pedrohrezende** [comment]
@unaghii A princípio sim, pois isso vai ficar na mão do cliente. Desta forma o cliente terá mais autonomia para  criar formulários com propósitos diferentes.

**Comment by unaghii** [comment]
Feito.

**Comment by pedrohrezende** [comment]
- Remover a mensagem de erro no topo "Olá, algo deu errado com o envio de seus dados... Alguns erros foram destacados a abaixo."
- O formulário está quebrando quando aparece a mensagem de erro logo abaixo do campo.

![image](https://cloud.githubusercontent.com/assets/1466491/12681126/315612b0-c694-11e5-8fdc-4e76f53f81d8.png)

**Comment by unaghii** [comment]
Corrigido.

**Comment by pedrohrezende** [comment]
Fala Victor, continua quebrando:

![image](https://cloud.githubusercontent.com/assets/1466491/12684363/9c91838c-c6a5-11e5-94f0-6a5730df4b59.png)

**Comment by unaghii** [comment]
@pedrohrezende dá uma testada de novo, deve ser cache de css, pq eu já havia arrumado.

**Comment by pedrohrezende** [comment]
Agora rodou 100%. Só mais um detalhe:
Está aparecendo 2 loaders e eles estão quebrando o form. Teria como ou remover os 2 loaders e deixar o botão "Ok" inativo enquanto enviar o form?

![image](https://cloud.githubusercontent.com/assets/1466491/12688121/408be72e-c6bb-11e5-98b3-c1ec639ba56d.png)

**Comment by unaghii** [comment]
Tirei o loader mas não rolou desabilitar o botão não porque o plugin não faz isso.
