### ISSUE TITLE
CTA do rodapé

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#6]
- Inserir o link no botão "Conversar com um especialista": http://tuttolabs.com.br/contato.html
- O texto do botão deve estar em caixa alta

![image](https://cloud.githubusercontent.com/assets/1466491/12593567/d8e73952-c458-11e5-816a-8b9acebb9230.png)

**Comment by unaghii** [comment]
Coloquei lá. Lembrando que isso está editável no Opções do tema ( http://bitnami-wordpress-85c3.cloudapp.net/wp-admin/admin.php?page=_options&tab=3 )
