### ISSUE TITLE
Detalhe de um vídeo

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#7]
O detalhe de um vídeo deve seguir o mesmo template de um post.

O topo precisa ter altura fixa. Hoje a altura está variando de acordo com o tamanho do título.

![image](https://cloud.githubusercontent.com/assets/1466491/12595445/7ce70b8c-c462-11e5-8511-4886c2ef1cda.png)

O usuário terá que subir uma foto relativa ao vídeo, assim podemos usá-la no topo da página e no thumbnail. É possível?
- Em vídeos relacionados o thumbnail não foi carregado:

![image](https://cloud.githubusercontent.com/assets/1466491/12593654/47f0a950-c459-11e5-8506-9de5e95c0b35.png)

**Comment by unaghii** [comment]
O thumbnail já está funcionando, é só colocar uma imagem destacada.

**Comment by pedrohrezende** [comment]
- O topo precisa funcionar da seguinte forma:
  O textos dentro do topo (titulo e autor do artigo) deve ficar SEMPRE centralizados na vertical - tanto no desktop, tablet e mobile. Uma sugestão é usar display:table e display:table-cell.
- É preciso ajustar o tamanho do texto e altura do header na versão mobile.

**Comment by unaghii** [comment]
Feito.

**Comment by pedrohrezende** [comment]
Na pastinha do Dropbox tem os PSDs simulando o mobile. Neles vc pode ver esses detalhes. Veja como fica o topo. A fonte reduz dentre outros pontos de mudança:

![image](https://cloud.githubusercontent.com/assets/1466491/12656234/3ec0e1e2-c5e4-11e5-9f62-d4dc16984e8e.png)

**Comment by unaghii** [comment]
Corrigido.

**Comment by pedrohrezende** [comment]
Usei o shortchode que vc me passou e inseri um vídeo do vimeo. Ele apresentou um player do Vimeo e outro do YouTube.

![image](https://cloud.githubusercontent.com/assets/1466491/12756014/f1b986be-c9b8-11e5-9a05-02cb4c3ee956.png)

**Comment by unaghii** [comment]
@pedrohrezende em que post você colocou? Não achei aqui

**Comment by pedrohrezende** [comment]
@unaghii Coloquei em vídeos

**Comment by unaghii** [comment]
Achei aqui. No caso de vídeo não precisa usar o shortcode. Já existe um campo pro link do vídeo logo abaixo do editor, é só colocar lá.
