### ISSUE TITLE
CTA Slider

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#8]
- Apresentar o CTA logo quando acabar o post.
- Não apresentar este CTA na versão mobile.
- A imagem do ebook ficou quebrada
- O ícone de fechar não apareceu
  ![image](https://cloud.githubusercontent.com/assets/1466491/12593717/988f21a2-c459-11e5-88f8-e1107ec79d8e.png)

**Comment by unaghii** [comment]
Feito.
