### ISSUE TITLE
Compartilhamento lateral

### ISSUE THREAD

**Issue by pedrohrezende** [pedrohrezende/tuttolabs#9]
Ficou faltando o compartilhamento nas redes sociais na lateral

![image](https://cloud.githubusercontent.com/assets/1466491/12593753/def5e3c4-c459-11e5-86f6-83f74a483d60.png)

Podemos usar este: http://www.addthis.com/

**Comment by unaghii** [comment]
Havia me esquecido disso mesmo, desculpe.

**Comment by pedrohrezende** [comment]
É possível alterar a ordem das redes?
1- Facebook
2- Twitter
3- Linkedin
4- Email

**Comment by unaghii** [comment]
@pedrohrezende o plugin não permite escolher as opções desse estilo, infelizmente.
Pegando direto do AddThis dá, porém meu usuário já usa outro estilo e não posso usar dois ao mesmo tempo, aparentemente.
Tem algum usuário que eu possa usar?

**Comment by pedrohrezende** [comment]
@unaghii Alterar isso é fácil? Posso solicitar para o cliente criar uma conta e depois atualizamos o plugin. O q acha?

**Comment by unaghii** [comment]
@pedrohrezende é fácil sim. Me arranja uma conta que eu coloco lá.

**Comment by pedrohrezende** [comment]
Segue os dados da conta criada pelo cliente:
Usuário: william.maruiama@tuttolabs.com.br
Senha: tutto

**Comment by unaghii** [comment]
Feito.
